### ISSUE TITLE
There was a problem with connecting to the Mongo DB.

### ISSUE THREAD

**Issue by TharukRenuja** [FayasNoushad/Movie-Info-Bot-V2#1]
There are some logs, same error happens every time & different mongo databases.
[movieinfo-logs.txt](https://github.com/FayasNoushad/Movie-Info-Bot-V2/files/7431895/movieinfo-logs-1635404315997.txt)

**Comment by TharukRenuja** [comment]
Is that only came to me😒.

**Comment by fayasnoushad** [comment]
I think your database link is error

**Comment by TharukRenuja** [comment]
> I think your database link is error

Okay
